### ISSUE TITLE
ollama 配置没起来

### ISSUE THREAD

**Issue by kksasa** [pdsuwwz/chatgpt-vue3-light-mvp#12]
还不太熟悉VUE框架，不知道是不是有啥没设置对。 ollama 还是没启动，报“undefined”

- API 里我换了地址和模型

export async function createOllama3Stylized (text) {
  const url = new URL(`http://xx.xxx.xxx.xxx:8000/api/chat`)
  
  const params = {
  }
  Object.keys(params).forEach(key => {
    url.searchParams.append(key, params[key])
  })

  const req = new Request(url, {
    mode: 'cors',
    method: 'post',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      'model': 'llama3.1:8b',

- chat.vue 里设置 

const defaultLLMTypeName: TransformStreamModelTypes = isMockDevelopment
  ? 'standard'
  : 'ollama3'

-  env.ts 
export const isMockDevelopment = false

**Comment by pdsuwwz** [comment]
@kksasa  你好，是否可以提供报错截图信息，或者先查看 ollama 是否为开启状态。本项目默认会调用 `spark` 请求函数，若调用 ollama 则可能需要同时更改以下位置的代码（[点击此处](https://github.com/pdsuwwz/chatgpt-vue3-light-mvp/blob/4887f64a1167051647e54bf8cc23e484ead77b4a/src/store/business/index.ts#L39)），改为调用 ollama 接口请求函数再尝试是否报错：

![image](https://github.com/user-attachments/assets/f8bc3d97-9c3a-4268-b1ed-afcc7c9a0387)

**Comment by pdsuwwz** [comment]
此 issue 已关闭。如有进一步问题，请重新打开或创建新 issue，谢谢。
