### ISSUE TITLE
核心在 MarkdownPreview 组件 能兼容dify的输出吗？特别是代码高亮风格。

### ISSUE THREAD

**Issue by glacierck** [pdsuwwz/chatgpt-vue3-light-mvp#14]
在考虑用dify作为llm服务后端，而本项目作为前端。

**Comment by pdsuwwz** [comment]
你好，我没有使用过 dify，不太清楚 dify 的 response 输出结构是什么样的，但如果是通用的 json，应该是能够兼容的，可以加一个 transform 函数尝试下, 代码在 [MarkdownPreview/transform/index.ts](https://github.com/pdsuwwz/chatgpt-vue3-light-mvp/blob/main/src/components/MarkdownPreview/transform/index.ts#L63)：

![image](https://github.com/user-attachments/assets/b3e11f26-53f0-49f6-a7b9-b00980e8fd7b)


以及对应的 Vue 组件：

https://github.com/pdsuwwz/chatgpt-vue3-light-mvp/blob/2430c5ed54c28ecf4777f2e0a5e51eb6d9a0c1e4/src/components/MarkdownPreview/index.vue#L137

其他的步骤按照 [README.md](https://github.com/pdsuwwz/chatgpt-vue3-light-mvp?tab=readme-ov-file#-%E6%A8%A1%E6%8B%9F%E7%9C%9F%E5%AE%9E-api-%E6%A8%A1%E5%BC%8F%E5%88%87%E6%8D%A2) 写的配置下就好。

**Comment by apconw** [comment]
可以参考这个开源项目: https://github.com/apconw/sanic-web
前端基于chatgpt-vue3-light-mvp项目修改

**Comment by pdsuwwz** [comment]
> 可以参考这个开源项目: https://github.com/apconw/sanic-web 前端基于chatgpt-vue3-light-mvp项目修改

@apconw 感谢提供实际用例场景😃

@glacierck  可以直接参考上面 AiAdventurer 分享的这个仓库，里面有完整的实现示例
